field: d8da346b-5693-434f-a6ec-4bd03a23eac8 # MenuHeaderButtons
fieldLayouts:
  80bcb439-ebb7-4ec1-b854-e54479e077d5:
    tabs:
      -
        elements:
          -
            fieldUid: e7f729c3-869b-428f-be5c-aec930553ce5 # ButtonText
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  e7f729c3-869b-428f-be5c-aec930553ce5: # ButtonText
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttontext
    instructions: ''
    name: ButtonText
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: buttontext
name: ButtonText
sortOrder: 1
