columnSuffix: null
contentColumnType: string
fieldGroup: 2f15e4fc-2165-48bc-9c39-e5266d07b5a0 # Common
handle: imagemainbackgound
instructions: 'Main Page background Image'
name: imageMainBackgound
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:62c63bcf-7533-4cb4-953b-652e6b3f5f63' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add center background image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:62c63bcf-7533-4cb4-953b-652e6b3f5f63' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
